Cosmotheka/Cosmotheka

xcell/mappers/mapper_dummy.py, xcell/tests/test_cls.py, xcell/tests/test_mapper_dummy.py
Let me know if you think of other tests we can add for the covariance.
=> added test for cov + option to vary fsky in dummy mapper

xcell/cls/cov.py, xcell/mappers/mapper_dummy.py, xcell/tests/test_cls.py
=> N_ell covariance marginalization

xcell/mappers/mapper_KV450.py, xcell/tests/test_mapper_kv450.py
Fixes sign convention for KV450 after computing the xcorr with DECALS
=> kv450 sign flip

xcell/cls/cl.py, xcell/cls/common.py, xcell/tests/test_cls.py
=> cl: improved read_symmetric

xcell/cls/cov.py
=> cov: fixed spin0 reshape + avoid repetition

xcell/cls/cov.py, xcell/cls/to_sacc.py
Implemented the multiplicative bias marginalization covariance matrix as in Eq. 37 of https://export.arxiv.org/pdf/2007.01844.
=> Multiplicative bias covariance marginalization

xcell/tests/test_mappers.py
=> tests for base mapper

run_cls.py, xcell/mappers/__init__.py, xcell/mappers/mapper_DELS.py, xcell/tests/test_mapper_dels.py
=> DELS tests

xcell/tests/test_mapper_dummy.py
=> Dummy unit tests

xcell/mappers/mapper_eBOSSQSO.py, xcell/tests/test_mapper_ebosqso.py
=> eBOSS unit tests

xcell/mappers/mapper_P18CMBK.py, xcell/tests/test_mapper_p18cmbk.py
=> Planck CMB lensing tests

xcell/mappers/mapper_KiDS1000.py, xcell/tests/test_mapper_k1000.py
=> KiDS 1000 unit tests

input/dels_k1000_ebossqus_p18cmb.yml
=> added ND input file

.github/workflows/ci.yml, .github/workflows/pip-requirements.txt, xcell/cls/data.py, xcell/cls/to_sacc.py, xcell/mappers/mapper_dummy.py, xcell/tests/test_tosacc.py
Closes #100 and #41. In progress
=> Test to_sacc

xcell/mappers/mapper_P18CMBK.py
Closes #127. Tested and same result.
=> p18cmbk: lite file with nside info (#127)

xcell/cls/data.py, xcell/tests/test_cls.py
Fix duplication of workspaces and cls (Closes #130) It will also close #129, ~~but still work in progress~~
=> Fix duplication of workspaces and cls (#130)

.github/workflows/ci.yml
The cache sometimes causes errors. Let's fix it!
=> ci: fix cache

xcell/cls/cl.py, xcell/tests/test_cls.py
Save the noiseless coupled Cell. Closes #136
=> cl: save the noiseless cl_cp

xcell/cls/cl.py, xcell/cls/cov.py, xcell/cls/data.py, xcell/mappers/mapper_dummy.py, xcell/tests/data/desy1_ebossqso_p18cmbk.yml, xcell/tests/test_cls.py, xcell/tests/test_data.py, xcell/tests/test_mapper_dummy.py
=> Cells from data for covariance

run_cls.py
=> run_cls: added short arguments

input/boss.yml, input/dels_k1000_ebossqus_p18cmb.yml, input/desy1_ebossqso_p18cmbk.yml, input/desy1_ebossqso_p18cmbk_512.yml, input/eboss.yml, input/kv450_1024.yml, input/yxgxk.yml, xcell/cls/cl.py, xcell/cls/cov.py, xcell/cls/data.py, xcell/cls/to_sacc.py, xcell/tests/data/desy1_ebossqso_p18cmbk.yml, xcell/tests/test_cls.py, xcell/tests/test_data.py, xcell/tests/test_tosacc.py
healpy section rename + nside unification under that section.
Closes #109
=> healpy section rename

input/dels_k1000_ebossqus_p18cmb.yml, run_cls.py, xcell/mappers/__init__.py, xcell/mappers/mapper_HSC_DR1wl.py, xcell/tests/test_mapper_HSCDR1wl.py
From https://arxiv.org/abs/2010.09717 and https://arxiv.org/abs/1809.09148
=> HSC DR1 shear sample

requirements.txt, xcell/cls/cl.py, xcell/cls/cov.py, xcell/tests/test_cls.py
=> Performance

xcell/cls/data.py, xcell/tests/data/conftest.yml, xcell/tests/data/des_b1.yml, xcell/tests/test_data.py
E.g. the yaml file now can be:
```
mappers:
mapper1: !include path/to/mapper1.yml
mapper2: !include path/to/mapper1.yml
mapper2: !include path/to/mapper1.yml
...
```
=> Loading parts of the master yml file from other yml files

xcell/cls/theory.py, xcell/tests/test_cls.py
Closes #199.
Let me know if you don't like the parameter name.
=> cls: added magnification

xcell/cls/data.py, xcell/mappers/mapper_2MPZ.py, xcell/mappers/mapper_ACT_base.py, xcell/mappers/mapper_ACT_compsept.py, xcell/mappers/mapper_CatWISE.py, xcell/mappers/mapper_DELS.py, xcell/mappers/mapper_DESY1gc.py, xcell/mappers/mapper_DESY1wl.py, xcell/mappers/mapper_HSC_DR1wl.py, xcell/mappers/mapper_KV450.py, xcell/mappers/mapper_KiDS1000.py, xcell/mappers/mapper_NVSS.py, xcell/mappers/mapper_P18CMBK.py, xcell/mappers/mapper_Planck_base.py, xcell/mappers/mapper_ROSAT.py, xcell/mappers/mapper_SDSS.py, xcell/mappers/mapper_WIxSC.py, xcell/mappers/mapper_base.py, xcell/tests/test_mapper_2MPZ.py, xcell/tests/test_mapper_ACT_all.py, xcell/tests/test_mapper_CatWISE.py, xcell/tests/test_mapper_HSCDR1wl.py, xcell/tests/test_mapper_SDSS.py, xcell/tests/test_mapper_WIxSC.py, xcell/tests/test_mapper_desy1wl.py, xcell/tests/test_mapper_k1000.py, xcell/tests/test_mapper_kv450.py
=> All mappers save masks

.github/workflows/ci.yml, xcell/mappers/mapper_DELS.py
=> mappers: DELS fixed nside consistency (issue228)

xcell/cls/data.py, xcell/tests/test_data.py, xcell/tests/test_mapper_desy1wl.py, xcell/tests/test_mapper_planck_all.py, xcell/tests/test_tosacc.py
=> Improve Data class

xcell/cls/cl.py, xcell/cls/cov.py, xcell/cls/data.py, xcell/cls/theory.py, xcell/cls/to_sacc.py
=> Documentation of the cls modules

setup.py, xcell/mappers/mapper_DESY3wl.py, xcell/mappers/mapper_base.py, xcell/mappers/mapper_dummy.py, xcell/tests/test_mapper_desy3wl.py, xcell/tests/test_mapper_dummy.py
Moved `remove_overlap` from `MapperDESY3wl` to `MapperBase`.
=> Remove overlap

xcell/mappers/mapper_DELS.py
Issue had to do with single vs. double precision, and an update to how either healpy or numpy deal with them.
=> DELS fixed

.readthedocs.yaml, docs/README.md, docs/source/conf.py
=> Added readthedocs support

cosmotheka/cls/cl.py, cosmotheka/cls/cov.py, cosmotheka/tests/test_cls.py, cosmotheka/tests/test_tools.py, run_cls.py
Just updating the code to the latest version of namaster
=> updating to latest namaster
